from pages.product_preishability import show_feature1
from pages.cust_purchase_expected_expiry import show_feature2
from pages.food_recommender import show_feature3
from pages.sentiment_analysis import show_feature4
from pages.dynamic_pricing_streamlit import dynamic_pricing_streamlit
from pages.closest_supermarket import main
